#!/bin/sh

source .secrets
# source .fake_secrets

# forge script script/DeployEth.s.sol:DeployEthScript \
#   --fork-url $REAL_ARB_RPC_URL  \
#   --private-key $REAL_ADMIN_PK \
#   --broadcast \
#   --verify \
#   --verifier-url $REAL_VERIFIER_URL \
#   --etherscan-api-key $ETHERSCAN_API_KEY

forge script script/DeployArb.s.sol:DeployArbScript \
  --fork-url $REAL_ARB_RPC_URL  \
  --private-key $REAL_ADMIN_PK \
  --broadcast \
  --verify \
  --verifier-url $REAL_VERIFIER_URL \
  --etherscan-api-key $ETHERSCAN_API_KEY

# forge verify-contract \
#     --chain-id $CHAIN_ID \
#     --num-of-optimizations 200 \
#     --etherscan-api-key $ETHERSCAN_API_KEY \
#     --verifier-url $REAL_VERIFIER_URL \
#     --watch \
#     --constructor-args \
#     $(cast abi-encode "constructor(address,address,address,address,address,address,address,address,uint256,uint256,uint256)" \
#      "$ETH" "$USDC" "$OPTION_PRICING" "$VOLATILITY" "$PRICE_ORACLE" "$ROUTER" "$FEE_DISTRIBUTOR" "$KEEPER" "$STRIKE_INCREMENT" "$OTM_PCT" "$EXPIRY") \
#     $ZDTE contracts/Zdte.sol:Zdte
