#!/bin/sh

set -e

source .secrets

cast send $ZDTE \
  --rpc-url $REAL_ARB_RPC_URL \
  --private-key $REAL_ADMIN_PK \
  "transferOwnership(address)" \
  $MASTER

# cast send $ZDTE \
#   --rpc-url $REAL_ARB_RPC_URL \
#   --private-key $REAL_ADMIN_PK \
#   "assignKeeperRole(address)" \
#   $keeper  
