#!/bin/sh

# set -euxo pipefail

source .secrets

cast send $ZDTE \
  --rpc-url $REAL_ARB_RPC_URL \
  --private-key $REAL_ADMIN_PK \
  "spreadOptionPosition(bool,uint256,uint256,uint256)" \
  false $POINT_ONE_ETHER $TWO_K $TWO_K_FIVE
